<?php  

/*
* requiring once the google api files and the realtime_os inc file
*/
require_once 'google-api-php-client/src/Google_Client.php';
require_once 'google-api-php-client/src/contrib/Google_AnalyticsService.php';
require_once 'realtime_os.inc';


/* 
* the main menu for realtime_openscholar
* displays active users on the OpenScholar site
*/
function realtime_os_menu() {
  $items = array();

  $items['realtime_os'] = array(
        'title' => 'OS dashboard real time',
        'description' => 'displays most active users',
 	'page callback' => 'active_users',
	'access callback' => TRUE,
    	);


  $items['realtime_os/active_users'] = array(
    'title' => 'Active Users',
    'type' => MENU_DEFAULT_LOCAL_TASK,
	'weight' => -10
  );

 return $items;
}

/*
* activer_users()
* no parameters. returns json_encoded active users of the OS sites
* calls the realtime_users function and the return value is json encoded
*/

 
 function active_users(){
     drupal_add_js(drupal_get_path('module', 'realtime_os') . '/realtime_os.js');
        
     $realtimeUsers = realtime_users();
     $realtimeNumbers = $realtimeUsers['rows'][0][0];
   //  $build = array(
   //     '#markup'=>	 '<div id="realtime_users"><b>Active Users:  <font color="green"><b> '.$realtimeUsers['rows'][0][0].'</b></font></b></div>');
		
    drupal_json_output($realtimeNumbers);

  }
  
  
