<?php  
require_once 'google-api-php-client/src/Google_Client.php';
require_once 'google-api-php-client/src/contrib/Google_AnalyticsService.php';
require_once 'google-api-php-client/src/contrib/Google_PlusService.php';

define('SCOPES','https://www.googleapis.com/auth/analytics.readonly');
define('PRIVATE_KEY','00c5052511a77ddfd2cde6a6d142072c5c369804-privatekey.p12');
define('CLIENT_ID','531026460268-ji89k4gqaa20fa3gj5cshkfvamdlqamf.apps.googleusercontent.com');
define('ACCESS_TYPE','offline_access');
define('SERVICE_GMAIL','531026460268-ji89k4gqaa20fa3gj5cshkfvamdlqamf@developer.gserviceaccount.com');
define('ANALYTICS_ID','ga:35141798');
define('START_DATE','2014-03-26');
define('END_DATE','2014-04-16');
define('METRICS_PAGEVIEWS','ga:pageviews' );
define('METRICS_VISITS','ga:visits');
define('ACTIVE_VISITORS', 'rt:activeVisitors');
define('SORT_PAGEVIEWS', '-ga:pageviews');
define('SORT_VISITS', '-ga:visits');
define('HEADER_VISITS', 'Most Visited Sites');
define('HEADER_VIEWS','Most viewed pages');
define('VISITED_NUMBER','Number Visited');
define('APP_HEADING','OpenScholar Board');
define('DIMENSIONS','ga:hostname');
define('MAX_RESULTS','25');


function os_board_menu() {
  $items = array();

  $items['os_board'] = array(
        'title' => 'OS dashboard',
        'description' => 'display most visited sites',
		'page callback' => 'most_visited_sites',
		'access callback' => TRUE,
  );

  $items['os_board/most-visited-sites'] = array(
		'title' => 'Most visited sites',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -10
  );

  $items['os_board/most-viewed-pages'] = array(
		'title' => 'Most viewed pages',
		'type' => MENU_LOCAL_TASK,
		'description' => 'displays most viewed pages',
		'page callback' => 'most_viewed_pages',
		'access callback' => TRUE,
		'weight' => -9  
  );
  
  $items['os_board/rt-visits'] = array(
		'title' => 'Real Time visits',
		'type' => MENU_LOCAL_TASK,
		'description' => 'displays real time visits.',
		'page callback' => 'real_time_visits',
		'access callback' => TRUE,
		'weight' => -8  
  );
  
  return $items;
}


function authen_client() {
  $file_contents = file_get_contents(drupal_get_path('module', 'os_board') . '/'.PRIVATE_KEY);
  $client = new Google_Client();
  $client->setApplicationName(APP_HEADING);
  $client->setAssertionCredentials(new Google_AssertionCredentials(SERVICE_GMAIL, array(SCOPES), $file_contents));
  $client->setClientId(CLIENT_ID);
  $client->setAccessType(ACCESS_TYPE);
  $service = new Google_AnalyticsService($client);
  return $service;
}


function most_visited_sites(){
  $output ='';
  $rows = array();
  $optparams = array ('dimensions' => DIMENSIONS,'sort' => SORT_VISITS,'max-results' => MAX_RESULTS);
  $service = authen_client();
  $header = array(HEADER_VISITS, VISITED_NUMBER);
  
  try {
    $results = $service->data_ga->get(ANALYTICS_ID, 
	                                  START_DATE, 
									  END_DATE, 
									  METRICS_VISITS, 
									  $optparams);
  }catch (apiServiceException $e) {
     $error = $e->getMessage();
  }
  
  $results = array('results' => $results);
  foreach($results['results']['rows'] as $result) {
    $rows[] = array($result[0],$result[1]);
  }
  
  $output .=  theme('table', array('header' => $header, 'rows' => $rows));
  return $output;
}


function most_viewed_pages(){
  $output ='';
  $rows = array();
  $optparams = array ('dimensions' => DIMENSIONS,'sort' => SORT_PAGEVIEWS,'max-results' => MAX_RESULTS);
  $header = array(HEADER_VIEWS, VISITED_NUMBER);
  $service = authen_client();
  
  try {
    $results = $service->data_ga->get(ANALYTICS_ID, 
	                                  START_DATE, 
									  END_DATE, 
									  METRICS_PAGEVIEWS, 
									  $optparams);
  }catch (apiServiceException $e) {
     $error = $e->getMessage();
  }
  
  $results = array('results' => $results);
  foreach($results['results']['rows'] as $result) {
    $rows[] = array($result[0],$result[1]);
  }
  
  $output .=  theme('table', array('header' => $header, 'rows' => $rows));
  return $output;
}

 
function real_time_visits() {
  $output ='';
  $rows = array();
  $header = array("Active Visitors");
  $optParams = array('dimensions' => 'rt:medium');
  $service = authen_client();
  
  try {
    $results = $service->data_realtime->get(ANALYTICS_ID,
	                                        ACTIVE_VISITORS,
		                                    $optParams);
  }catch (apiServiceException $e) {
     $error = $e->getMessage();
  }
	 
  foreach($results as $result) {
    $rows[] = $result;
  }
	  
  $final = array($rows[7]);
  $output .=  theme('table', array('header' => $header, 'rows' => $final));
  return $output;
}
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 